# Site settings
title: Rankie
email: rankiejiang97@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A minimalist personal website showcasing my work and thoughts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://boiledbroccoli.github.io" # the base hostname & protocol for your site
twitter_username: yourusername
github_username: boiledbroccoli
orcid_id: 0009-0005-2868-324X

# Personal info
name: "Rankie Jiang"
bio: |
I am a PhD student in Psychology at Zhejiang University with a bachelor's degree in Applied Psychology from East China Normal University (ECNU). Currently, I am a visiting researcher at the [Language, Cognition and Learning (LCL) Lab](https://langcomplab.github.io/) under [Dr. Cynthia Siew](https://x.com/csqsiew)'s supervision at the National University of Singapore. 
My research focuses on language processing mechanisms, particularly Chinese character and word recognition—the core of my doctoral thesis. Beyond my thesis work, I am also interested in the broader sociolinguistic dimensions of language use, examining how language shapes and is shaped by cultural practices and social perceptions. Recently, I have been expanding into computational approaches, exploring Large Language Model (LLM) agents for social simulation, which bridges my traditional psycholinguistic research with cutting-edge AI methodologies to model linguistic behavior in social contexts.
keywords: "language processing, psycholinguistic, social linguistics"
cv_pdf: "/assets/cv.pdf"
profile_image: "/assets/avatar.jpg"

# Social links
social:
  github: boiledbroccoli
  orcid: 0009-0005-2868-324X
  custom_link: 
    text: "OSF"
    url: "https://osf.io/ms9fq"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  news:
    output: false
    sort_by: date

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Pagination
paginate: 10
paginate_path: "/notes/page:num/"

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"